version: '2'
services:
  weeklyshop-app:
    image: weeklyshop
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://weeklyshop-postgresql:5432/WeeklyShop
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://weeklyshop-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://weeklyshop-elasticsearch:9200
    ports:
      - 8080:8080
  weeklyshop-postgresql:
    extends:
      file: postgresql.yml
      service: weeklyshop-postgresql
  weeklyshop-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: weeklyshop-elasticsearch
